services:
  backend:
    image: openjdk:25-ea-4-jdk-oraclelinux9
    container_name: order
    ports:
      - "8080:8080"
    depends_on:
      - order_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order_db:5432/orderDB
    volumes:
      - ./target:/app
      - ./logs:/logs
    command: [ "java", "-jar", "/app/order-0.0.1-SNAPSHOT.jar" ]

  order_db:
    image: postgres:14.17
    container_name: order_db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: orderDB
    ports:
      - "5432:5432"

  loki:
    image: grafana/loki:3.5.0
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:10.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
