services:
  backend:
    image: openjdk:25-ea-4-jdk-oraclelinux9
    container_name: order
    ports:
      - "8080:8080"
    depends_on:
      - order_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order_db:5432/orderDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    volumes:
      - ./target:/app
      - ./logs:/logs
    command: [ "java", "-jar", "/app/order-0.0.1-SNAPSHOT.jar" ]

  order_db:
    image: postgres:14.17
    container_name: order_db
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: orderDB
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

